### ISSUE TITLE
Load map in mobile devices

### ISSUE THREAD

**Issue by baumannzone** [apiaddicts/apidaysmad17#10]
If you go to https://apiaddicts.github.io/apidaysmad17/ in a mobile device, google map is not shown because an error.
We need to fix/change this behavior and be able to see the google map in the main page (📱)

**Comment by Asjas** [comment]
Hi, After playing around with the website I noticed that the problem is when the website gets under a certain size (about less than 800px) the url that is requested for the background image is throwing a 403 error in the console. After a bit of research I saw that it could be the Google Maps API rejecting the request.

https://stackoverflow.com/questions/45859039/google-static-map-without-api-key-gives-403forbidden-error

Would this be something that I could fix or is it something to do with the Static Maps API not being configured?

I did notice that the URL in the console is missing the API key at the end of the URL which could cause the problem.

**Comment by baumannzone** [comment]
First all, thank for your interest. 
As I knew, the problem is because some `document.write` when the device size is less than 768px
And that's "forbidden" : Check [this post](https://developers.google.com/web/updates/2016/08/removing-document-write) by google

**Comment by baumannzone** [comment]
Closing
